In [61]:
# -*- coding: utf8 -*-
from os.path import expanduser
home = expanduser("~")
annee="24"
nKalaba="K1"
repertoire=home+"/sDrive/Cours/Bordeaux/L1-LinguistiqueGenerale/00-ProjetKalaba/"+annee+"-%s"%nKalaba
serie=repertoire+"/"
complementPhrases=""
phrasesFichiers=["Phrases","Ordre","Traductions"]
#phrasesFichiers=["Phrases"]
nomComptes=serie+complementPhrases+"Comptes.csv"
nomLexique=serie+"Lexique-S2.pkl"
debug=False

In [62]:
#########################IMPORTS############################################
import codecs, optparse
import re, random
import sys,os,time
import string
import yaml, warnings
import ParFuMor as PFM
from ParFuMor import *
import pickle
import pandas as pd

In [63]:
with open(nomLexique, 'rb') as input:
   PFM.lexique = pickle.load(input)

In [64]:
with open(serie+"MorphoSyntax.yaml", 'r') as stream:
    morphosyntax=yaml.load(stream)
contractions=morphosyntax["Contractions"]

/opt/anaconda3/envs/python2/lib/python2.7/site-packages/ipykernel_launcher.py:2: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.

In [65]:
def compterLexique(exemplesPhrases):
    debug=0
    lexiquePhrases={}
    lexiqueComptes={}
    for nExemple,exemple in enumerate(exemplesPhrases):
        nPhrase=nExemple+1
        motsExemple=[mot for mot in re.split(ur"[\s',]",exemple) if mot!=""]
        for mot in motsExemple:
            if mot in PFM.lexique.formeLexeme:
                lexeme=PFM.lexique.formeLexeme[mot][0]
                if not lexeme in lexiqueComptes: lexiqueComptes[lexeme]=0
                lexiqueComptes[lexeme]+=1
                if not lexeme in lexiquePhrases: lexiquePhrases[lexeme]=set()
                lexiquePhrases[lexeme].add(nPhrase)
                if debug: print lexeme,
            elif mot[-1] in "DP":
                lexeme=PFM.lexique.formeLexeme[mot[:-1]][0]
                if not lexeme in lexiqueComptes: lexiqueComptes[lexeme]=0
                lexiqueComptes[lexeme]+=1
                if not lexeme in lexiquePhrases: lexiquePhrases[lexeme]=set()
                lexiquePhrases[lexeme].add(nPhrase)
                if debug: print lexeme,                
            elif mot in contractions:
                for element in contractions[mot]:
                    lexeme=PFM.lexique.formeLexeme[element][0]
                    if not lexeme in lexiqueComptes: lexiqueComptes[lexeme]=0
                    lexiqueComptes[lexeme]+=1
                    if not lexeme in lexiquePhrases: lexiquePhrases[lexeme]=set()
                    lexiquePhrases[lexeme].add(nPhrase)
                    if debug: print lexeme,
            else:
                lexeme=u"#%s#"%mot
                if not lexeme in lexiqueComptes: lexiqueComptes[lexeme]=0
                lexiqueComptes[lexeme]+=1
                if not lexeme in lexiquePhrases: lexiquePhrases[lexeme]=set()
                lexiquePhrases[lexeme].add(nPhrase)
                if debug: print lexeme,
        if debug: print
    return lexiqueComptes,lexiquePhrases

In [66]:
def stripLex(lex):
    return lex.strip("#")

In [67]:
def printLexPhrases(lexPhrases):
    for lex in sorted(lexPhrases.keys()):
        print stripLex(lex.split(".")[0]),", ".join(["(%d)"%num for num in sorted(lexPhrases[lex])])

In [68]:
def printLexComptes(lexComptes):
    for lex in sorted(lexComptes, key=lexComptes.get,reverse=True):
        print stripLex(lex.split(".")[0]), lexComptes[lex]

In [69]:
dfLexComptes=[]

In [70]:
for nFichier,locFichier in enumerate(phrasesFichiers):
    fichier=serie+complementPhrases+locFichier+".csv"
    with codecs.open(fichier, 'r', encoding="utf8") as input:
       exemplesPhrases = input.readlines()
    exemplesPhrases=[exemple.strip().strip(".") for exemple in exemplesPhrases if not exemple.startswith("#")]
    lexComptes, lexPhrases=compterLexique(exemplesPhrases)
    print fichier
    dfLexComptes.append(pd.DataFrame.from_dict(lexComptes,orient="index"))
    dfLexComptes[nFichier].columns=[locFichier]
    dfLexComptes[nFichier]["lexeme"]=dfLexComptes[nFichier].index
    dfLexComptes[nFichier]=dfLexComptes[nFichier][["lexeme",locFichier]]
    if debug:
        print "lexComptes"
        printLexComptes(lexComptes)
        print
        print "lexPhrases"
        printLexPhrases(lexPhrases)
        print
        print
        print

/Users/gilles/sDrive/Cours/Bordeaux/L1-LinguistiqueGenerale/00-ProjetKalaba/24-K1/Phrases.csv
/Users/gilles/sDrive/Cours/Bordeaux/L1-LinguistiqueGenerale/00-ProjetKalaba/24-K1/Ordre.csv
/Users/gilles/sDrive/Cours/Bordeaux/L1-LinguistiqueGenerale/00-ProjetKalaba/24-K1/Traductions.csv

In [71]:
dfLexComptes[1]

                        lexeme  Ordre
six                        six      1
transformer.V1  transformer.V1      2
envahir.V1          envahir.V1      1
jour.M                  jour.M      1
grimoire.N          grimoire.N      2
acheter.V1          acheter.V1      7
aller.V1              aller.V1      1
dernier-N.N        dernier-N.N      1
souffrance.F      souffrance.F      3
maître.N              maître.N      1
enfant.N              enfant.N      9
inquiéter.V1      inquiéter.V1      1
donner.V1            donner.V1     14
rouge                    rouge     12
table.F                table.F     15
Nicole.F              Nicole.F     16
Agathos.F            Agathos.F      1
construction.N  construction.N      2
crapaud.N            crapaud.N      3
noir                      noir     25
être.V1                être.V1      1
montrer.V1          montrer.V1      9
coup.N                  coup.N      2
partir.V2            partir.V2      1
colère.F              colère.F      4
mère.F                  mère.F      1
faire.V2              faire.V2      1
jardiner.V1        jardiner.V1      1
différent            différent      3
cacher.V2            cacher.V2      1
...                        ...    ...
douleur.M            douleur.M      1
demande.F            demande.F      1
Elphaba.F            Elphaba.F      1
plaine.N              plaine.N      8
allumer.V1          allumer.V1      1
Kaleb.M                Kaleb.M      7
IND                        IND    138
donjon.N              donjon.N      4
feu.F                    feu.F      1
gros                      gros     16
recouvrir.V1      recouvrir.V1      1
maison.F              maison.F     33
préparer.V2        préparer.V2      1
treize                  treize      1
gorge.M                gorge.M      2
redevenir.V2      redevenir.V2      1
lit.F                    lit.F     19
nombreux              nombreux      1
sept                      sept      1
lancer.V2            lancer.V2      7
nourrir.V1          nourrir.V1      1
#nouvellE#          #nouvellE#      1
main.N                  main.N      5
voleuse.F            voleuse.F      1
#approchèrent#  #approchèrent#      1
transpercer.V1  transpercer.V1      2
effrayé                effrayé      6
remercier.V1      remercier.V1      1
gargouille.N      gargouille.N      4
passer.V1            passer.V1      1

[265 rows x 2 columns]

In [72]:
df12=dfLexComptes[0].merge(dfLexComptes[1],how="outer").merge(dfLexComptes[2],how="outer")
df12[pd.notnull(df12["Traductions"])].sort_values(by="Ordre")

             lexeme  Phrases  Ordre  Traductions
187       entrer.V1      NaN    6.0         12.0
146        chatte.F      NaN    6.0         92.0
163         fruit.N      NaN    7.0        190.0
172        viande.M      NaN    7.0       1314.0
184           thé.M      NaN    7.0         52.0
99       acheter.V1      NaN    7.0       2454.0
191       offrir.V2      NaN    7.0       1952.0
261       lancer.V2      NaN    7.0        584.0
213         balai.M      NaN    8.0        684.0
216            pour      NaN    8.0       1154.0
219          maigre      NaN    8.0         88.0
250        plaine.N      NaN    8.0        752.0
154       poisson.M      NaN    9.0       1530.0
207          quatre      NaN    9.0         86.0
108      montrer.V1      NaN    9.0         80.0
201       Katisha.F      NaN   10.0       1992.0
185       manger.V2      NaN   10.0         12.0
218            sous      NaN   10.0        270.0
231           jaune      NaN   10.0       1492.0
147        boire.V1      NaN   10.0         54.0
202           trois      NaN   11.0        360.0
180          café.N      NaN   11.0         24.0
83   chasser-Act.V1      4.0   11.0        674.0
6             rouge      7.0   12.0        322.0
188       dormir.V2      NaN   14.0        132.0
25        donner.V1      9.0   14.0        116.0
69           devant      4.0   14.0       1758.0
228    supporter.V2      NaN   15.0         10.0
193           œuf.N      NaN   15.0        220.0
52        tomber.V2     10.0   15.0       1186.0
..              ...      ...    ...          ...
123       cuisine.N      NaN   15.0       1332.0
116       coussin.F      NaN   15.0        298.0
254            gros      NaN   16.0        282.0
104        Nicole.F      NaN   16.0       1430.0
166         Nabil.M      NaN   18.0       2070.0
217       chambre.N      NaN   18.0         36.0
168        coyote.F      NaN   18.0       3524.0
230        garçon.M      NaN   18.0       1106.0
258           lit.F      NaN   19.0        262.0
33        village.N     14.0   21.0       1414.0
138        souris.M      NaN   22.0        598.0
161    infirmière.F      NaN   22.0       2156.0
236      autruche.F      NaN   23.0       1886.0
59            blanc     11.0   24.0        600.0
38              sur      7.0   24.0        448.0
7              noir     16.0   25.0        232.0
85            grand     15.0   26.0        116.0
60             avec     12.0   29.0       2042.0
178          chat.M      NaN   30.0       1116.0
57          fille.F     18.0   31.0       1774.0
90         maison.F      9.0   33.0       1986.0
239      chasseur.M      NaN   34.0       4838.0
76            petit     18.0   38.0       2344.0
47                à     24.0   51.0       4022.0
72             dans     30.0   52.0       1296.0
31              DEM     28.0   53.0       6990.0
84             deux     29.0   97.0       7200.0
17               de     53.0  118.0       8296.0
50              IND     63.0  138.0       5448.0
34              DEF    248.0  402.0      12124.0

[62 rows x 4 columns]

In [73]:
df12.to_csv(path_or_buf=nomComptes,sep="\t",encoding="utf8")

In [74]:
nomComptes

'/Users/gilles/sDrive/Cours/Bordeaux/L1-LinguistiqueGenerale/00-ProjetKalaba/24-K1/Comptes.csv'

In [75]:
i=0
for v in PFM.lexique.vedettes.values():
    if v not in dfLexComptes[1].lexeme.tolist():
        i+=1
        print i,v

1 pleurer-Act.V1
2 PRO
3 pendre.V1
4 lever.V1
5 accueillir.V1
6 voler-Act.V1
7 manquer-Med.V2
8 retourner.V2
9 ressusciter.V2
10 interroger.V1
11 approcher.V1
12 tourner-Mov.V1
13 revenir.V2
14 placer.V2
15 arrêter.V1
16 attraper.V2
17 excuser.V2
18 demander.V2
19 illustrer.V2
20 sortir-Mov.V2