In [1]:
# -*- coding: utf8 -*-
from os.path import expanduser
home = expanduser("~")
annee="25"
nKalaba="K1"
repertoire=home+"/sDrive/Cours/Bordeaux/L1-LinguistiqueGenerale/00-ProjetKalaba/"+annee+"-%s"%nKalaba
serie=repertoire+"/"
complementPhrases=""
phrasesFichiers=["Phrases","Ordre","Traductions","Ecrit"]
# phrasesFichiers=["Ordre"]
nomComptes=serie+complementPhrases+"Comptes.csv"
nomLexique=serie+"Lexique-S2.pkl"
debug=False

In [2]:
#########################IMPORTS############################################
import codecs, optparse
import re, random
import sys,os,time
import string
import yaml, warnings
import ParFuMor as PFM
from ParFuMor import *
import pickle
import pandas as pd

In [3]:
with open(nomLexique, 'rb') as input:
   PFM.lexique = pickle.load(input)

In [4]:
with open(serie+"MorphoSyntax.yaml", 'r') as stream:
    morphosyntax=yaml.safe_load(stream)
contractions=morphosyntax["Contractions"]

In [5]:
def compterLexique(exemplesPhrases):
    debug=0
    lexiquePhrases={}
    lexiqueComptes={}
    for nExemple,exemple in enumerate(exemplesPhrases):
        nPhrase=nExemple+1
        motsExemple=[mot for mot in re.split(ur"[\s',]",exemple) if mot!=""]
        for mot in motsExemple:
            if mot in PFM.lexique.formeLexeme:
                lexeme=PFM.lexique.formeLexeme[mot][0]
                if not lexeme in lexiqueComptes: lexiqueComptes[lexeme]=0
                lexiqueComptes[lexeme]+=1
                if not lexeme in lexiquePhrases: lexiquePhrases[lexeme]=set()
                lexiquePhrases[lexeme].add(nPhrase)
                if debug: print lexeme,
            elif mot[-1] in "DP":
                lexeme=PFM.lexique.formeLexeme[mot[:-1]][0]
                if not lexeme in lexiqueComptes: lexiqueComptes[lexeme]=0
                lexiqueComptes[lexeme]+=1
                if not lexeme in lexiquePhrases: lexiquePhrases[lexeme]=set()
                lexiquePhrases[lexeme].add(nPhrase)
                if debug: print lexeme,                
            elif mot in contractions:
                for element in contractions[mot]:
                    lexeme=PFM.lexique.formeLexeme[element][0]
                    if not lexeme in lexiqueComptes: lexiqueComptes[lexeme]=0
                    lexiqueComptes[lexeme]+=1
                    if not lexeme in lexiquePhrases: lexiquePhrases[lexeme]=set()
                    lexiquePhrases[lexeme].add(nPhrase)
                    if debug: print lexeme,
            else:
                lexeme=u"#%s#"%mot
                if not lexeme in lexiqueComptes: lexiqueComptes[lexeme]=0
                lexiqueComptes[lexeme]+=1
                if not lexeme in lexiquePhrases: lexiquePhrases[lexeme]=set()
                lexiquePhrases[lexeme].add(nPhrase)
                if debug: print lexeme,
        if debug: print
    return lexiqueComptes,lexiquePhrases

In [6]:
def stripLex(lex):
    return lex.strip("#")

In [7]:
def printLexPhrases(lexPhrases):
    for lex in sorted(lexPhrases.keys()):
        print stripLex(lex.split(".")[0]),", ".join(["(%d)"%num for num in sorted(lexPhrases[lex])])

In [8]:
def printLexComptes(lexComptes):
    for lex in sorted(lexComptes, key=lexComptes.get,reverse=True):
        print stripLex(lex.split(".")[0]), lexComptes[lex]

In [9]:
dfLexComptes=[]

In [10]:
for nFichier,locFichier in enumerate(phrasesFichiers):
    fichier=serie+complementPhrases+locFichier+".csv"
    with codecs.open(fichier, 'r', encoding="utf8") as input:
       exemplesPhrases = input.readlines()
    exemplesPhrases=[exemple.strip().strip(".") for exemple in exemplesPhrases if not exemple.startswith("#")]
    lexComptes, lexPhrases=compterLexique(exemplesPhrases)
    print fichier
    dfLexComptes.append(pd.DataFrame.from_dict(lexComptes,orient="index"))
    dfLexComptes[nFichier].columns=[locFichier]
    dfLexComptes[nFichier]["lexeme"]=dfLexComptes[nFichier].index
    dfLexComptes[nFichier]=dfLexComptes[nFichier][["lexeme",locFichier]]
    if debug:
        print "lexComptes"
        printLexComptes(lexComptes)
        print
        print "lexPhrases"
        printLexPhrases(lexPhrases)
        print
        print
        print

/Users/gilles/sDrive/Cours/Bordeaux/L1-LinguistiqueGenerale/00-ProjetKalaba/25-K1/Phrases.csv
/Users/gilles/sDrive/Cours/Bordeaux/L1-LinguistiqueGenerale/00-ProjetKalaba/25-K1/Ordre.csv
/Users/gilles/sDrive/Cours/Bordeaux/L1-LinguistiqueGenerale/00-ProjetKalaba/25-K1/Traductions.csv
/Users/gilles/sDrive/Cours/Bordeaux/L1-LinguistiqueGenerale/00-ProjetKalaba/25-K1/Ecrit.csv

In [12]:
dfLexComptes[1]

                              lexeme  Ordre
nuire.V2                    nuire.V2      2
transformer.V1        transformer.V1      2
envahir.V2                envahir.V2      2
grimoire.N                grimoire.N      2
acheter.V1                acheter.V1      7
dernier-N.N              dernier-N.N      2
souffrance.F            souffrance.F      3
maître.N                    maître.N      2
enfant.N                    enfant.N     10
donner.V2                  donner.V2     14
#;#                              #;#      1
rouge                          rouge     12
table.F                      table.F     15
Nicole.F                    Nicole.F     16
Agathos.F                  Agathos.F      1
construction.N        construction.N      2
crapaud.N                  crapaud.N      4
noir                            noir     25
être.V2                      être.V2      1
obscurité.M              obscurité.M      1
sorcier.N                  sorcier.N      9
coup.N                        coup.N      2
partir.V1                  partir.V1      1
colère.F                    colère.F      4
mère.F                        mère.F      2
corps.F                      corps.F      2
jardiner.V1              jardiner.V1      1
différent                  différent      3
cacher.V2                  cacher.V2      1
compter.V1                compter.V1      1
...                              ...    ...
Elphaba.F                  Elphaba.F      2
plaine.N                    plaine.N      8
allumer.V2                allumer.V2      1
Kaleb.M                      Kaleb.M      7
IND                              IND    146
légende.N                  légende.N      2
donjon.N                    donjon.N      4
maison.M                    maison.M     34
feu.F                          feu.F      2
gros                            gros     16
noyer.V2                    noyer.V2      1
offrir.V1                  offrir.V1      7
redevenir.V1            redevenir.V1      1
treize                        treize      3
gorge.M                      gorge.M      2
lit.F                          lit.F     19
nourrir.V2                nourrir.V2      1
nombreux                    nombreux      2
voter.V2                    voter.V2      1
lancer.V1                  lancer.V1      7
#elles#chattesP##  #elles#chattesP##      2
main.N                        main.N      5
aller.V2                    aller.V2      1
voleuse.F                  voleuse.F      2
transpercer.V2        transpercer.V2      2
effrayé                      effrayé      6
remercier.V1            remercier.V1      2
reconstruire.V1      reconstruire.V1      1
gargouille.N            gargouille.N      4
passer.V1                  passer.V1      1

[267 rows x 2 columns]

In [95]:
dfOrdre=dfLexComptes[1]
print dfOrdre[(dfOrdre.Ordre==1)
    &(dfOrdre.index.str.contains("[V]"))
    ].to_string()

# dfOrdre[(dfOrdre.Ordre==1)]

                          lexeme  Ordre
être.V2                  être.V2      1
partir.V1              partir.V1      1
jardiner.V1          jardiner.V1      1
cacher.V2              cacher.V2      1
compter.V1            compter.V1      1
découvrir.V1        découvrir.V1      1
porter.V1              porter.V1      1
mourir.V2              mourir.V2      1
approcher.V2        approcher.V2      1
rêvasser.V1          rêvasser.V1      1
préparer.V2          préparer.V2      1
connaître.V1        connaître.V1      1
faire.V1                faire.V1      1
retourner.V1        retourner.V1      1
hurler.V1              hurler.V1      1
détester.V1          détester.V1      1
courir.V1              courir.V1      1
recouvrir.V2        recouvrir.V2      1
voir.V2                  voir.V2      1
posséder.V1          posséder.V1      1
surplomber.V1      surplomber.V1      1
voler-Act.V1        voler-Act.V1      1
brûler-Med.V1      brûler-Med.V1      1
chasser-Mov.V2    chasser-Mov.V2      1
sortir-Mov.V1      sortir-Mov.V1      1
avoir.V1                avoir.V1      1
raconter.V1          raconter.V1      1
embrasser.V1        embrasser.V1      1
reconnaître.V2    reconnaître.V2      1
inquiéter.V1        inquiéter.V1      1
descendre.V2        descendre.V2      1
vivre.V1                vivre.V1      1
brûler.V2              brûler.V2      1
enlever.V2            enlever.V2      1
rejoindre.V2        rejoindre.V2      1
pleurer.V1            pleurer.V1      1
échanger.V1          échanger.V1      1
enfermer.V2          enfermer.V2      1
voler.V2                voler.V2      1
allumer.V2            allumer.V2      1
noyer.V2                noyer.V2      1
redevenir.V1        redevenir.V1      1
nourrir.V2            nourrir.V2      1
voter.V2                voter.V2      1
aller.V2                aller.V2      1
reconstruire.V1  reconstruire.V1      1
passer.V1              passer.V1      1

In [18]:
df12=dfLexComptes[1].merge(dfLexComptes[2],how="outer")
df12.loc[(df12.Ordre==1)&(df12.Traductions.notnull())]

             lexeme  Ordre  Traductions
14        Agathos.F    1.0       5162.0
19      obscurité.M    1.0       3156.0
26      jardiner.V1    1.0        672.0
29       compter.V1    1.0       2996.0
41           oeil.F    1.0      10104.0
60        mourir.V2    1.0         78.0
63         héroïque    1.0      17296.0
90     connaître.V1    1.0        696.0
91         faire.V1    1.0       6384.0
100       hurler.V1    1.0         18.0
109     chasseuse.F    1.0       8736.0
114       courir.V1    1.0        314.0
122    recouvrir.V2    1.0        588.0
126     posséder.V1    1.0       1008.0
150      harmonie.M    1.0       3224.0
156   brûler-Med.V1    1.0        276.0
158  chasser-Mov.V2    1.0        216.0
165        légume.F    1.0      77214.0
170     raconter.V1    1.0      35868.0
171    embrasser.V1    1.0       3276.0
173  reconnaître.V2    1.0       3654.0
178           autre    1.0       4296.0
179    inquiéter.V1    1.0       2040.0
180    descendre.V2    1.0        144.0
184         homme.M    1.0       3276.0
187         disparu    1.0      20966.0
189             par    1.0       2496.0
193       brûler.V2    1.0       1152.0
194          robe.M    1.0        876.0
197         femme.F    1.0       9450.0
201         dégât.M    1.0       2418.0
203         matin.N    1.0        174.0
205      blessure.N    1.0        504.0
208    rejoindre.V2    1.0       2496.0
215          bras.F    1.0       8550.0
221     échanger.V1    1.0         36.0
231            cinq    1.0      77690.0
232         dernier    1.0      33318.0
233         méchant    1.0       4538.0
234       douleur.M    1.0       6470.0
235       demande.F    1.0       5412.0
236        voler.V2    1.0       2160.0
239      allumer.V2    1.0       8918.0
247        noyer.V2    1.0       4482.0
249    redevenir.V1    1.0        216.0
253      nourrir.V2    1.0       1620.0
259        aller.V2    1.0        546.0
266       passer.V1    1.0       2286.0

In [97]:
df12=dfLexComptes[3].merge(dfLexComptes[1],how="outer")#.merge(dfLexComptes[2],how="outer")
df12[pd.notnull(df12["Ecrit"])].sort_values(by="Ordre")

                  lexeme  Ecrit  Ordre
66               voir.V2    1.0    1.0
119           allumer.V2    1.0    1.0
118              méchant    2.0    1.0
117          enfermer.V2    1.0    1.0
110                  par    1.0    1.0
99              vivre.V1    1.0    1.0
94                 autre    1.0    1.0
85          voler-Act.V1    1.0    1.0
59             courir.V1    2.0    1.0
53           détester.V1    1.0    1.0
51             hurler.V1    1.0    1.0
49              faire.V1    1.0    1.0
38           rêvasser.V1    1.0    1.0
36         sortir-Mov.V1    1.0    1.0
34          approcher.V2    1.0    1.0
31          retourner.V1    1.0    1.0
133            passer.V1    2.0    1.0
9              Agathos.F    2.0    1.0
6                    #;#    1.0    1.0
11               être.V2    4.0    1.0
0         transformer.V1    3.0    2.0
106           planter.V1    3.0    2.0
105             combat.N    1.0    2.0
100               sort.N    4.0    2.0
47             courageux    1.0    2.0
48           chercher.V1    2.0    2.0
12                coup.N    2.0    2.0
89           protéger.V2    1.0    2.0
56             sauter.V1    2.0    2.0
88            prendre.V2    2.0    2.0
..                   ...    ...    ...
45            arriver.V2    1.0   15.0
93               arbre.N   15.0   15.0
69             tomber.V2    4.0   15.0
8               Nicole.F    1.0   16.0
124                 gros    1.0   16.0
101            chambre.N    1.0   18.0
71              coyote.F    1.0   18.0
43             village.N   16.0   21.0
50                   sur   11.0   25.0
10                  noir    6.0   25.0
78                 blanc    6.0   25.0
114                grand    2.0   26.0
81                  avec   21.0   30.0
75               fille.F    5.0   31.0
123             maison.M    8.0   34.0
111           chasseur.M    7.0   34.0
104                petit    8.0   38.0
98                  dans   13.0   53.0
41                   DEM   12.0   55.0
60                     à   13.0   56.0
113                 deux   30.0   98.0
22                    de   29.0  130.0
122                  IND   43.0  146.0
44                   DEF  131.0  422.0
2           #il#esprit##    1.0    NaN
16       #ils#enfANTsD##    1.0    NaN
17           #il#Kaleb##    1.0    NaN
90         #elle#Freja##    2.0    NaN
121  #elles#sorcièresD##    3.0    NaN
131         #il#dragon##    1.0    NaN

[134 rows x 3 columns]

In [73]:
df12.to_csv(path_or_buf=nomComptes,sep="\t",encoding="utf8")

In [74]:
nomComptes

'/Users/gilles/sDrive/Cours/Bordeaux/L1-LinguistiqueGenerale/00-ProjetKalaba/24-K1/Comptes.csv'

In [75]:
i=0
for v in PFM.lexique.vedettes.values():
    if v not in dfLexComptes[1].lexeme.tolist():
        i+=1
        print i,v

1 pleurer-Act.V1
2 PRO
3 pendre.V1
4 lever.V1
5 accueillir.V1
6 voler-Act.V1
7 manquer-Med.V2
8 retourner.V2
9 ressusciter.V2
10 interroger.V1
11 approcher.V1
12 tourner-Mov.V1
13 revenir.V2
14 placer.V2
15 arrêter.V1
16 attraper.V2
17 excuser.V2
18 demander.V2
19 illustrer.V2
20 sortir-Mov.V2